Transposing a matrix

In [15]:
import numpy as np

m = np.random.randn(2, 5)

tm = m.T

print("Matrix A")
print(m)
print("Transposed of Matrix A")
print(tm)

Matrix A
[[ 1.03302339  0.99939403  0.90900992  0.50641871  1.54130451]
 [-0.23866605 -0.79110031  1.7467033  -0.28121673 -0.53509764]]
Transposed of Matrix A
[[ 1.03302339 -0.23866605]
 [ 0.99939403 -0.79110031]
 [ 0.90900992  1.7467033 ]
 [ 0.50641871 -0.28121673]
 [ 1.54130451 -0.53509764]]


Generating Special Matrices

In [23]:
import numpy as np

I = np.eye(4)
print("Identical Matrix")
print(I)
O = np.ones((3, 5))
print("Ones Matrix")
print(O)
Z = np.zeros((4, 3))
print(Z)

Identical Matrix
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Ones Matrix
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Diagonal Matrix

In [24]:
import numpy as np

d = np.diag([3, 4, 2, 4])
print(d)

[[3 0 0 0]
 [0 4 0 0]
 [0 0 2 0]
 [0 0 0 4]]


In [26]:
import numpy as np

dn = np.random.randn(4)
d = np.diag(dn)
print(d)

[[ 0.34604132  0.          0.          0.        ]
 [ 0.         -1.12299225  0.          0.        ]
 [ 0.          0.         -0.23501641  0.        ]
 [ 0.          0.          0.         -1.35893137]]


Augmented Matrix

In [34]:
import numpy as np

m1 = np.random.randn(4, 3)
m2 = np.random.randn(4, 3)

print("First Matrix")
print(m1)
print("Second Matrix")
print(m2)
print("Concatenation of First and Second matrices")

# axis = 1 will put matrices side by side where axis = 0 will put them on top of each other
c = np.concatenate((m1, m2), axis = 1)
print(c)

First Matrix
[[ 0.21176478 -0.57693593 -0.25757971]
 [ 0.17809423  0.89122766 -1.57183074]
 [-1.98443703 -2.08537573 -0.93221775]
 [ 0.64199949  0.47486581  0.23391727]]
Second Matrix
[[ 0.60591924 -1.35859953  1.02472686]
 [ 1.07196383  0.23660658 -0.5905552 ]
 [-0.84177101  1.11376501 -1.76651739]
 [-1.60237939 -1.09591229 -0.83308286]]
Concatenation of First and Second matrices
[[ 0.21176478 -0.57693593 -0.25757971]
 [ 0.17809423  0.89122766 -1.57183074]
 [-1.98443703 -2.08537573 -0.93221775]
 [ 0.64199949  0.47486581  0.23391727]
 [ 0.60591924 -1.35859953  1.02472686]
 [ 1.07196383  0.23660658 -0.5905552 ]
 [-0.84177101  1.11376501 -1.76651739]
 [-1.60237939 -1.09591229 -0.83308286]]


Extracting traingular matrices

In [36]:
import numpy as np

m = np.random.randn(4, 3)

print("Matrix A")
print(m)

print("Up triangle matrix of Matrix A")
u = np.triu(m)
print(u)
print("Down triangle matrix of Matrix A")
d = np.tril(m)
print(d)

Matrix A
[[ 1.37675252 -0.6515474   2.35551762]
 [-0.23877722 -0.67868565 -2.25023654]
 [-0.38143184  1.19469776 -0.20382951]
 [ 0.28878179 -0.2893312  -0.78604274]]
Up triangle matrix of Matrix A
[[ 1.37675252 -0.6515474   2.35551762]
 [ 0.         -0.67868565 -2.25023654]
 [ 0.          0.         -0.20382951]
 [ 0.          0.          0.        ]]
Down triangle matrix of Matrix A
[[ 1.37675252  0.          0.        ]
 [-0.23877722 -0.67868565  0.        ]
 [-0.38143184  1.19469776 -0.20382951]
 [ 0.28878179 -0.2893312  -0.78604274]]
