Dot Product of two vectors

In [2]:
import numpy as np

v1 = np.array([1, 2, 3, 4])
v2 = np.array([3, 4, 2, 3])
vr = np.dot(v1, v2)
print(vr)

29


Associative Property with a scalar

In [4]:
import numpy as np

v1 = np.array([1, 2, 3])
v2 = np.array([4, 3, 2])
s = 10

vr1 = np.dot(v1, v2) * s

vr2 = np.dot(v1*s, v2*s)
print("s * ( v1 * v2 )")
print(vr1)
print("( (s * v1) ( s * v2 ) )")
print(vr2)

s * ( v1 * v2 )
160
( (s * v1) ( s * v2 ) )
1600


Associative Property between vectors

In [10]:
import numpy as np

v1 = np.array([1, 2, 3])
v2 = np.array([4, 3, 2])
v3 = np.array([3, 2, 3])

print("v1 (v2 * v3)")
vr1 = np.dot(v1, np.dot(v2, v3))
print(vr1)
print("(v1 * v2) v3")
vr2 = np.dot(np.dot(v1, v2), v3)
print(vr2)

v1 (v2 * v3)
[24 48 72]
(v1 * v2) v3
[48 32 48]


Commutative Property

In [11]:
import numpy as np

v1 = np.array([1, 2, 3])
v2 = np.array([4, 3, 2])

print("(v1 * v2)")
vr1 = np.dot(v1, v2)
print(vr1)
print("(v2 * v1)")
vr2 = np.dot(v2, v1)
print(vr2)

(v1 * v2)
16
(v2 * v1)
16


Distributive Property

In [14]:
import numpy as np

v1 = np.array([1, 2, 3])
v2 = np.array([4, 3, 2])
v3 = np.array([3, 2, 3])

print("v1 (v2 + v3)")
vr1 = np.dot(v1, (v2 + v3))
print(vr1)
print("(v1 * v2) + (v1 * v3)")
vr2 = np.dot(v1, v2) + np.dot(v1, v3)
print(vr2)

v1 (v2 + v3)
32
(v1 * v2) + (v1 * v3)
32


Linear weighted combinations

In [6]:
import numpy as np
l1 = 1
l2 = 2
l3 = -3
v1 = np.array( [ 4 , 5 , 1 ] )
v2 = np.array( [ -4 , 0 , -4] )
v3 = np.array( [ 1 , 3 , 2 ] )
l1 * v1 + l2 * v2 + l3 * v3


array([ -7,  -4, -13])

Outer Product

In [8]:
import numpy as np

v1 = np.array([2, 3, 4, 5])
v2 = np.array([4, 3, 2])
op = np.outer(v1, v2)
print(op)

[[ 8  6  4]
 [12  9  6]
 [16 12  8]
 [20 15 10]]


Element wise Outer product (Hadamard Multiplication)

In [1]:
import numpy as np

v1 = np.array([2, 4, 5, 3])
v2 = np.array([4, 3, 2, 1])

r = v1 * v2 

print(r)

[ 8 12 10  3]


Unit vector (finding vector norm)

In [2]:
import numpy as np

lv = np.array([2, 5, 4, 7])
nv = np.linalg.norm(lv)

print(nv)

9.695359714832659
